<h2 style='color:purple' align='center'>Naive Bayes Tutorial Part 1: Predicting survival from titanic crash</h2>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("E:/GIM/Term III/ML/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [4]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [5]:
#inputs.Sex = inputs.Sex.map({'male': 1, 'female': 2})

In [6]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [7]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

**I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female**

In [8]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [9]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [10]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [11]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [13]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [14]:
model.fit(X_train,y_train)

GaussianNB()

In [15]:
model.score(X_test,y_test)

0.7910447761194029

In [16]:
X_test[0:10]

Pclass        Age      Fare  female
315       3  26.000000    7.8542       1
92        1  46.000000   61.1750       0
168       1  29.699118   25.9250       0
595       3  36.000000   24.1500       0
458       2  50.000000   10.5000       1
700       1  18.000000  227.5250       1
218       1  32.000000   76.2917       1
615       2  24.000000   65.0000       1
427       2  19.000000   26.0000       1
543       2  32.000000   26.0000       0

In [17]:
y_test[0:10]

315    1
92     0
168    0
595    0
458    1
700    1
218    1
615    1
427    1
543    1
Name: Survived, dtype: int64

In [18]:
model.predict(X_test[0:10])

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [19]:
model.predict_proba(X_test[:10])

array([[4.81402031e-01, 5.18597969e-01],
       [6.40990284e-01, 3.59009716e-01],
       [7.94822462e-01, 2.05177538e-01],
       [9.68465072e-01, 3.15349281e-02],
       [3.15296334e-01, 6.84703666e-01],
       [7.97339901e-10, 9.99999999e-01],
       [2.74370996e-02, 9.72562900e-01],
       [1.31181845e-01, 8.68818155e-01],
       [2.74617935e-01, 7.25382065e-01],
       [9.30591878e-01, 6.94081223e-02]])

**Calculate the score using cross validation**

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.76      , 0.744     , 0.816     , 0.75806452, 0.72580645])

#### SVM

In [21]:
#SVM
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 10)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=10)

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[143  16]
 [ 42  67]]


0.7835820895522388

In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel = 'linear', random_state = 0),X_train, y_train, cv=5)

array([0.816     , 0.832     , 0.808     , 0.77419355, 0.70967742])

In [25]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel = 'rbf', random_state = 0),X_train, y_train, cv=5)

array([0.808     , 0.8       , 0.832     , 0.7983871 , 0.72580645])

### Decision tree

In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 10)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[135  24]
 [ 29  80]]


0.8022388059701493

In [28]:
from sklearn.model_selection import cross_val_score
cross_val_score(DecisionTreeClassifier(criterion = 'entropy', random_state = 10),X_train, y_train, cv=5)

array([0.776     , 0.784     , 0.8       , 0.70967742, 0.72580645])

#### Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 10)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=10)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[147  12]
 [ 34  75]]


0.8283582089552238

In [31]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 10),X_train, y_train, cv=5)

array([0.792     , 0.816     , 0.84      , 0.77419355, 0.78225806])

### Logistic Regression

In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 10)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=10)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[145  14]
 [ 41  68]]


0.7947761194029851

In [34]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(random_state = 10),X_train, y_train, cv=5)

array([0.824     , 0.768     , 0.824     , 0.79032258, 0.70967742])